### ISSUE TITLE
[Module Listing Request]: `nuxt-yandex-metrika`

### ISSUE THREAD

**Issue by NickRisinger** [nuxt/modules#1149]
### Description

module for integrating nuxt and Yandex Metrica

## Meta

```yaml
name: nuxt-yandex-metrika
description: A lightweight module for integrating Yandex.Metrika into Nuxt, enabling easy analytics setup and tracking user interactions
repo: yandex-unofficial/nuxt-yandex-metrika
npm: 'nuxt-ym'
icon: http-status.svg
github: https://github.com/yandex-unofficial/nuxt-yandex-metrika
website: https://github.com/yandex-unofficial/nuxt-yandex-metrika
learn_more: ''
category: Analytics
type: 3rd-party
maintainers:
  - name: Nick Risinger
    github: https://github.com/NickRisinger
compatibility:
  nuxt: '>=3.0.0'
```

### Repository

https://github.com/yandex-unofficial/nuxt-yandex-metrika

### npm

https://www.npmjs.com/package/nuxt-ym

### Nuxt Compatibility

Nuxt 3
