### ISSUE TITLE
[Module Listing Request]: `nuxt-music-flow`

### ISSUE THREAD

**Issue by ndragun92** [nuxt/modules#1180]
## Description
Module for audio player component with playlist and waveform visualization based of [`vue-music-flow`](https://www.npmjs.com/package/vue-music-flow) package.

### Meta
```yaml
name: nuxt-music-flow
description: Nuxt 3 module for audio player component with playlist and waveform visualization.
repo: ndragun92/nuxt-music-flow
npm: nuxt-music-flow
icon: nuxt-music-flow.png
github: https://github.com/ndragun92/nuxt-music-flow
website: https://vue-music-flow-docs.vercel.app/usage#nuxt
learn_more: https://vue-music-flow-docs.vercel.app/demo
category: Libraries
type: 3rd-party
maintainers:
  - name: Nemanja Dragun
    github: ndragun92
    twitter: nemanjadragun
compatibility:
  nuxt: '>=3.0.0'
```
Repository
https://github.com/ndragun92/nuxt-music-flow

npm
https://www.npmjs.com/package/nuxt-music-flow

Nuxt Compatibility
Nuxt 3
