### ISSUE TITLE
[Module Listing Request]: `@peterbud/nuxt-query`

### ISSUE THREAD

**Issue by peterbud** [nuxt/modules#1184]
# Description

Nuxt module for TanStack Query (FKA Vue Query) with Nuxt DevTools integration

## Meta

```yaml
name: nuxt-query
description: Nuxt module for TanStack Query (FKA Vue Query) with Nuxt DevTools integration
repo: peterbud/nuxt-query
npm: '@peterbud/nuxt-query'
icon: nuxt-query.svg
github: https://github.com/peterbud/nuxt-query
website: https://github.com/peterbud/nuxt-query#readme
learn_more: https://tanstack.com/query/latest/docs/framework/vue/overview
category: Libraries
type: 3rd-party
maintainers:
  - name: Peter Budai
    github: peterbud
    bluesky: peterbud.bsky.social
compatibility:
  nuxt: '>=3.0.0'
  requires: {}
```

Repository
https://github.com/peterbud/nuxt-query

npm
https://www.npmjs.com/package/@peterbud/nuxt-query

Nuxt Compatibility
Nuxt 3
