### ISSUE TITLE
Add `nuxt-envalidate`

### ISSUE THREAD

**Issue by manuelhenke** [nuxt/modules#426]
# Add `nuxt-envalidate`
## Features
This a dead simple wrapper module for the library [envalidate](https://github.com/af/envalid) which validates your environment variables, provides default values and inject them to where you want. This module stores them back to `process.env` and `options.env`. It can go hand in hand with `@nuxtjs/dotenv`.

## Repository
https://github.com/manuelhenke/nuxt-envalid

## Definitions
```yml
name: nuxt-envalidate
description: Validates your env variables and loads them cleaned into your application context
repo: manuelhenke/nuxt-envalid
npm: 'nuxt-envalid'
icon: dotenv.png
github: https://github.com/manuelhenke/nuxt-envalid
website: https://github.com/manuelhenke/nuxt-envalid
learn_more: https://www.npmjs.com/package/nuxt-envalid
category: Extensions
type: community
maintainers:
  - name: Manuel Henke
    github: manuelhenke
compatibility:
  nuxt: ^2.0.0
  requires: {}
```
