### ISSUE TITLE
Add `nuxt-vue3-google-signin`

### ISSUE THREAD

**Issue by kasvith** [nuxt/modules#429]
## Features
`nuxt-vue3-google-signin` allows users to integrate google sign-in hassle-free. This module uses [`vue3-google-signin`](https://vue3-google-signin.syetalabs.io/) under the hood

## Repository
 https://github.com/syetalabs/nuxt-vue3-google-signin

## Icon
https://github.com/syetalabs/vue3-google-signin/blob/main/docs/public/logo.svg

## Definitions

```yaml
name: nuxt-vue3-google-signin
description: Empower your Nuxt app with Google Sign-in hassle-free
repo: syetalabs/nuxt-vue3-google-signin
npm: 'nuxt-vue3-google-signin'
github: https://github.com/syetalabs/nuxt-vue3-google-signin
website: https://vue3-google-signin.syetalabs.io/
learn_more: https://vue3-google-signin.syetalabs.io/
category: Libraries
type: community
maintainers:
  - name: Kasun Vithanage
    github: kasvith
compatibility:
  nuxt: ^3.0.0
  requires: {}
```
