### ISSUE TITLE
Add `nuxt-monaco-editor`

### ISSUE THREAD

**Issue by e-chan1007** [nuxt/modules#434]
Hi, there. I'd like to add [`nuxt-monaco-editor`](https://e-chan1007.github.io/nuxt-monaco-editor).
Since this is my first module, I would appreciate any help and feedback!

## Features

It is a very simple module that integrates [`monaco-editor`](https://microsoft.github.io/monaco-editor/).
With a built-in component, you can embed the editor easily.

## Repository
https://github.com/e-chan1007/nuxt-monaco-editor

## Definitions
```yml
name: nuxt-monaco-editor
description: Integrate monaco-editor with Nuxt
repo: e-chan1007/nuxt-monaco-editor
npm: nuxt-monaco-editor
github: https://github.com/e-chan1007/nuxt-monaco-editor
website: https://github.com/e-chan1007/nuxt-monaco-editor
learn_more: https://e-chan1007.github.io/nuxt-monaco-editor
category: Libraries
type: 3rd-party
maintainers:
  - name: e-chan1007
    github: e-chan1007
compatibility:
  nuxt: ^3.0.0
  requires: {}
```
