### ISSUE TITLE
[Module Listing Request]: `nuxt-gtm`

### ISSUE THREAD

**Issue by LouisMazel** [nuxt/modules#610]
### Description

# @zadigetvoltaire/nuxt-gtm

## Description

- A Nuxt.js module to implement and manage Google Tag Manager

## Documentation

- https://github.com/zadigetvoltaire/nuxt-gtm#readme

## Meta

```yml
name: gtm
description: A Nuxt.js module for Google Tag Manager
repo: @zadigetvoltaire/nuxt-gtm
npm: '@zadigetvoltaire/nuxt-gtm'
icon: https://github.com/zadigetvoltaire/nuxt-gtm/blob/main/assets/nuxt-gtm.png?raw=true
github: https://github.com/zadigetvoltaire/nuxt-gtm
website: https://github.com/zadigetvoltaire/nuxt-gtm
category: Analytics
type: community
maintainers:
  - name: Zadig&Voltaire Team
    github: https://github.com/zadigetvoltaire
compatibility:
  nuxt: ^3.0.0
```

### Repository

https://github.com/zadigetvoltaire/nuxt-gtm

### npm

https://www.npmjs.com/package/@zadigetvoltaire/nuxt-gtm

### Nuxt Compatibility

Nuxt 3
