### ISSUE TITLE
[Module Listing Request]: `nuxt-well-known`

### ISSUE THREAD

**Issue by LouisMazel** [nuxt/modules#611]
### Description

# @zadigetvoltaire/nuxt-well-known

## Description

- A Nuxt.js module to add well-known URIs using middlewares

## Documentation

- https://github.com/zadigetvoltaire/nuxt-well-known#readme

## Meta

```yml
name: well-known
description: A Nuxt.js module to add well-known URIs using middlewares
repo: @zadigetvoltaire/nuxt-well-known
npm: '@zadigetvoltaire/nuxt-well-known'
icon: https://github.com/zadigetvoltaire/nuxt-gtm/blob/main/assets/nuxt-well-known.png?raw=true
github: https://github.com/zadigetvoltaire/nuxt-well-known
website: https://github.com/zadigetvoltaire/nuxt-well-known
category: SEO
type: community
maintainers:
  - name: Zadig&Voltaire Team
    github: https://github.com/zadigetvoltaire
compatibility:
  nuxt: ^3.0.0
```

### Repository

https://github.com/zadigetvoltaire/nuxt-well-known

### npm

https://www.npmjs.com/package/@zadigetvoltaire/nuxt-well-known

### Nuxt Compatibility

Nuxt 3
