### ISSUE TITLE
Add nuxt-jsonapi module

### ISSUE THREAD

**Issue by patrickcate** [nuxt/modules#62]
Would it be possible to add [nuxt-jsonapi](https://github.com/patrickcate/nuxt-jsonapi)? I believe this is the information you need:

```yml
name: nuxt-jsonapi
description: Easy JSON:API client integration for Nuxt.js
repo: patrickcate/nuxt-jsonapi
npm: nuxt-jsonapi
icon: ''
github: 'https://github.com/patrickcate/nuxt-jsonapi'
website: 'https://github.com/patrickcate/nuxt-jsonapi'
learn_more: ''
category: Request
type: 3rd-party
maintainers:
  - name: Patrick Cate
    github: patrickcate
    avatar: 'https://avatars0.githubusercontent.com/u/6277206?v=4'
```

The logo is:

![Nuxt JSON:API logo](https://raw.githubusercontent.com/patrickcate/nuxt-jsonapi/main/example/static/nuxt-jsonapi-logo.svg)
